### ISSUE TITLE
docs & i18n

### ISSUE THREAD

**Issue by lnnt** [kudzu-cms/kudzu-cli#11]
How to generate docs?
```
$ go run main.go
2021/02/22 03:47:26 [Plugins] Build
2021/02/22 03:47:26     Loading: .plugins/page.so
2021/02/22 03:47:26     Attaching: .plugins/page.so
2021/02/22 03:47:26 [Plugins] Done

View documentation offline at: http://localhost:8081
Server listening at http://localhost:8080 for HTTP requests...
Visit http://localhost:8080/admin to get started.
```
![docs 404](https://user-images.githubusercontent.com/22957642/108636533-da4db280-74c0-11eb-9e4c-f0a14a76e3d9.png)

---
How to change English to another language?Such as "Configuration","Admin Users","Uploads"...Thank you very much!
![i18n](https://user-images.githubusercontent.com/22957642/108636762-58f71f80-74c2-11eb-92e5-e963a3c6ef94.png)

**Comment by bobbygryzynger** [comment]
@stepbystep2 the original docs at https://docs.ponzu-cms.org/ are still mostly relevant but I haven't been maintaining them at this point since they're, increasingly, outdated. They'll need some revisions once things get to a stable place. When that'll be, I can't say. 

The original implementation didn't have localization support and support for it isn't in my immediate plans.
